name: Learning GitHub Script
on:
  issues:
    types: [opened]
  issue_comment:
    type: [created, edited]
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const token = ${{ github.token }};
